FROM cassandra:3
LABEL maintainer "Tim Curless <tim.curless@thinkahead.com>"

COPY ./migration.sh /tmp
RUN chmod u+x /tmp/migration.sh

# 7000: intra-node communication
# 7001: TLS intra-node communication
# 7199: JMX
# 9042: CQL
# 9160: thrift service
EXPOSE 7000 7001 7199 9042 9160
CMD /tmp/migration.sh
